server:
  port: 6677

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://120.79.50.150:3306/hello?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver